- hosts: all
  tasks:
  - name: set timezone
    shell: timedatectl set-timezone America/Detroit

  - name: Install NTP
    apt: name=chrony state=latest 
    tags: ntp
 
  - name: Copy over the NTP configuration
    template: src=/var/lib/awx/projects/update/resources/chronyclient.conf dest=/etc/chrony.conf
    notify:
    - restart chronyd
    tags: ntp
 
  - name: Make sure NTP is started up
    service: name=chronyd state=started enabled=yes
    tags: ntp

  - name: Sync hwclock
    shell: hwclock -w
    tags: ntp
    
  handlers:
   - name: restart chronyd
     service: name=chronyd state=restarted