- hosts: all
  tasks:
  - name: set timezone
    shell: timedatectl set-timezone America/Detroit

  - name: Install NTP
    yum: name=chrony state=installed 
    tags: ntp
 
  - name: Copy over the NTP configuration
    template: src=/var/lib/awx/projects/update/resources/chronyserver.conf dest=/etc/chrony.conf
    notify:
    - restart chronyd
    tags: ntp
 
  - name: Make sure NTP is started up
    service: name=chronyd state=running enabled=yes
    tags: ntp

  - name: Sync hwclock
    shell: hwclock -w
    tags: ntp
