- hosts: centos
  tasks:
  - name: Install snmp
    yum: name=net-snmp state=installed
    become: yes
  - name: Sync snmp
    template: src=/etc/snmp/snmpd.conf  dest=/etc/snmp/snmpd.conf
    become: yes
  - name: Restrart  snmp
    service: name=snmpd  state=restarted

